version: '3'

services:
  db:
    container_name: db-pizzaria
    image: postgres
    tty: true
    ports:
    - '54322:5432'
    restart: always
    environment:
      - POSTGRES_PASSWORD=p4ss0rd
      - POSTGRES_USER=pizzaadmin
      - POSTGRES_DB=pizzariadb
