version: '3'

services:
  app:
    container_name: api_pizzaria
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/home/node/app
    command: npm run start:dev
    ports:
      - '5000:5000'
    restart: always
    env_file:
      - ./src/common/envs/development.env
    depends_on:
      - db

  db:
    container_name: db-pizzaria
    image: postgres
    tty: true
    ports:
    - '5432:5432'
    restart: always
    environment:
      - POSTGRES_DB=pizzaria
      - POSTGRES_PASSWORD=pizzaria
      - POSTGRES_USER=userroot
volumes:
  db-data: {}
