version: '3'

services:
  app:
    container_name: pizzaria-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    container_name: pizzaria-db
    build: .docker/postgres
    image: postgres
    ports:
      - "5432:5432"
    tty: true
    restart: always
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=pizzaria
      - POSTGRES_PASSWORD=123456
volumes:
  db-data: {}
