version: '3'

services:
  app:
    container_name: api-vdt-hub-b2b
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/home/node/app
    command: npm run start:dev
    ports:
      - '5000:5000'
    restart: always
    env_file:
      - ./src/common/envs/development.env
    depends_on:
      - db

  db:
    container_name: db-vdt-hub-b2b
    image: mysql
    tty: true
    ports:
    - '3306:3306'
    restart: always
    env_file:
      - src/common/envs/development.env
volumes:
  db-data: {}
